#!/bin/bash

export OBERON=.:../Sym64

#../../Bin/ofront+ -m ../Test/TestUnix.Mod
#errCode=$?
#if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi

gcc TestUnix.c -o TestUnix.x -I ../Obj64 -I ../C -L .. -lOfront64
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
  
./TestUnix.x
