#!/bin/bash

export OBERON=.:../Sym64

../../Bin64/ofront+ -m ../Test/TestFileExists.Mod
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi

gcc TestFileExists.c -o TestFileExists.x -I ../Obj64 -I ../../../Lib/Mod -L .. -lOfront
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
  
./TestFileExists.x TestFileExists.x
