#!/bin/bash

export OBERON=.:../Sym64

../../Bin64/ofront+ -m ../Test/TestOoc2RandomNumbers.Mod
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi

gcc TestOoc2RandomNumbers.c -o TestOoc2RandomNumbers.x -I ../Obj64 -I ../C -L .. -lOfront64
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
  
./TestOoc2RandomNumbers.x
