#!/bin/bash

export OBERON=.:../Sym64

../../Bin64/ofront+ -m ../Test/TestArgs.Mod
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi

gcc TestArgs.c -o TestArgs.x -I ../Obj64 -I ../C -L .. -lOfront64
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
  
./TestArgs.x arg1 "ARG 2" "__!@#$_arg3_&%*()-="
