#!/bin/bash

export OBERON=.:../Sym

../../Bin/ofront+ -m TestFileExists.Mod
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi

gcc TestFileExists.c -o TestFileExists.x -I ../Obj -I ../../../Lib/Mod -L .. -lOfront
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
  
./TestFileExists.x TestFileExists.x
