#!/bin/bash

export OBERON=.:../Sym

../../Bin/ofront+ -m TestOoc2RandomNumbers.Mod
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi

gcc TestOoc2RandomNumbers.c -o TestOoc2RandomNumbers.x -I ../Obj -I ../C -L .. -lOfront
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
  
./TestOoc2RandomNumbers.x
