#!/bin/bash

export OBERON=.:../Sym

../../Bin/ofront+ -m TestArgs.Mod
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi

gcc TestArgs.c -o TestArgs.x -I ../Obj -I ../../../Lib/Mod -L .. -lOfront
errCode=$?
if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
  
./TestArgs.x arg1 "ARG 2" "__!@#$_arg3_&%*()-="
